[build]
  # Build command (Vite projects use "npm run build")
  command = "npm run build"
  
  # Publish directory (Vite outputs to "dist")
  publish = "dist"
  
  # Optional: Node.js version (use latest LTS)
  # environment = { NODE_VERSION = "18" }

[build.environment]
  # Example environment variables
  # NODE_ENV = "production"
  # REACT_APP_API_URL = "https://api.yoursite.com"
  # Add your environment variables here or use Netlify dashboard

[[redirects]]
  # Handle React Router (SPA) - redirect all routes to index.html
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets for 1 year
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"